// mobile/app/(tabs)/dashboard.tsx
import { useState, useEffect, useCallback } from 'react';
import { View, Text, Pressable, StyleSheet, ScrollView } from 'react-native';
import { obd2 } from '../../lib/api';
import { createOBD2Socket, SensorData } from '../../lib/ws';

const THEME = {
  bg: '#0a0e14',
  surface: '#141920',
  border: '#1e2530',
  green: '#33ff33',
  amber: '#ffb833',
  red: '#ff4444',
  text: '#c5cdd8',
  muted: '#6b7a8d',
};

function GaugeCard({
  label,
  value,
  unit,
  warn,
  crit,
}: {
  label: string;
  value: number | null;
  unit: string;
  warn?: number;
  crit?: number;
}) {
  const display = value !== null && value !== undefined ? String(value) : '--';
  let color = THEME.green;
  if (value !== null && crit && value >= crit) color = THEME.red;
  else if (value !== null && warn && value >= warn) color = THEME.amber;

  return (
    <View style={styles.gauge}>
      <Text style={[styles.gaugeValue, { color }]}>{display}</Text>
      <Text style={styles.gaugeUnit}>{unit}</Text>
      <Text style={styles.gaugeLabel}>{label}</Text>
    </View>
  );
}

export default function DashboardScreen() {
  const [sensorData, setSensorData] = useState<SensorData | null>(null);
  const [connected, setConnected] = useState(false);
  const [error, setError] = useState('');
  const [ws, setWs] = useState<ReturnType<typeof createOBD2Socket> | null>(null);

  const connect = useCallback(() => {
    setError('');
    const socket = createOBD2Socket(
      (data) => {
        setSensorData(data);
        setConnected(true);
      },
      (err) => setError(err),
    );
    setWs(socket);
  }, []);

  const disconnect = useCallback(() => {
    ws?.close();
    setWs(null);
    setSensorData(null);
    setConnected(false);
  }, [ws]);

  useEffect(() => {
    return () => {
      ws?.close();
    };
  }, [ws]);

  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      <View style={styles.header}>
        <Text style={styles.title}>OBD-II Dashboard</Text>
        {connected ? (
          <Pressable style={styles.btn} onPress={disconnect}>
            <Text style={styles.btnText}>Disconnect</Text>
          </Pressable>
        ) : (
          <Pressable style={[styles.btn, styles.btnPrimary]} onPress={connect}>
            <Text style={[styles.btnText, { color: THEME.green }]}>Connect</Text>
          </Pressable>
        )}
      </View>

      {error ? <Text style={styles.error}>{error}</Text> : null}

      <View style={styles.gaugeGrid}>
        <GaugeCard label="RPM" value={sensorData?.rpm ?? null} unit="rpm" warn={4500} crit={5500} />
        <GaugeCard label="Speed" value={sensorData?.speed_mph ?? null} unit="mph" />
        <GaugeCard
          label="Coolant"
          value={sensorData?.coolant_temp_f ?? null}
          unit="°F"
          warn={220}
          crit={240}
        />
        <GaugeCard label="Throttle" value={sensorData?.throttle_pct ?? null} unit="%" />
        <GaugeCard
          label="Load"
          value={sensorData?.engine_load_pct ?? null}
          unit="%"
          warn={85}
          crit={95}
        />
        <GaugeCard label="Intake" value={sensorData?.intake_temp_f ?? null} unit="°F" warn={150} />
      </View>

      {!sensorData && !error && (
        <Text style={styles.hint}>Connect to OBD-II to see live engine data.</Text>
      )}
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: THEME.bg },
  content: { padding: 16 },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  title: { color: THEME.text, fontFamily: 'monospace', fontWeight: '700', fontSize: 16 },
  btn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: THEME.border,
    backgroundColor: THEME.surface,
  },
  btnPrimary: { borderColor: '#1a8c1a', backgroundColor: 'rgba(51,255,51,0.08)' },
  btnText: { color: THEME.text, fontFamily: 'monospace', fontSize: 12 },
  error: {
    color: THEME.red,
    backgroundColor: 'rgba(255,68,68,0.08)',
    padding: 8,
    borderRadius: 4,
    fontFamily: 'monospace',
    fontSize: 12,
    marginBottom: 12,
  },
  gaugeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    justifyContent: 'center',
  },
  gauge: {
    width: 100,
    backgroundColor: THEME.surface,
    borderColor: THEME.border,
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    alignItems: 'center',
  },
  gaugeValue: { fontSize: 22, fontWeight: '700', fontFamily: 'monospace' },
  gaugeUnit: { fontSize: 10, color: THEME.muted, fontFamily: 'monospace' },
  gaugeLabel: { fontSize: 11, color: THEME.muted, fontFamily: 'monospace', marginTop: 4 },
  hint: { color: THEME.muted, fontFamily: 'monospace', fontSize: 12, textAlign: 'center', marginTop: 40 },
});

// src/frontend/src/routes/dashboard/+page.svelte
<script>
	import { onMount, onDestroy } from 'svelte';
	import { sensorData, obd2Connected } from '$lib/stores.js';
	import { obd2 } from '$lib/api.js';
	import { createOBD2Socket } from '$lib/ws.js';
	import SensorGauge from '../../components/SensorGauge.svelte';

	let ws = null;
	let error = '';
	let dtcs = [];

	onMount(async () => {
		try {
			const status = await obd2.status();
			obd2Connected.set(status.enabled && status.connected);
		} catch {
			// ignore
		}
	});

	function connectLive() {
		error = '';
		ws = createOBD2Socket(
			(data) => sensorData.set(data),
			(err) => { error = err; }
		);
	}

	function disconnectLive() {
		ws?.close();
		ws = null;
		sensorData.set(null);
	}

	async function readDTCs() {
		try {
			const res = await obd2.dtcs();
			dtcs = res.dtcs || [];
		} catch (err) {
			error = err.message;
		}
	}

	onDestroy(() => {
		ws?.close();
	});
</script>

<div class="dashboard">
	<div class="header">
		<h2>OBD-II Dashboard</h2>
		<div class="controls">
			{#if ws}
				<button on:click={disconnectLive}>Disconnect</button>
			{:else}
				<button class="primary" on:click={connectLive}>Connect Live</button>
			{/if}
			<button on:click={readDTCs}>Read DTCs</button>
		</div>
	</div>

	{#if error}
		<div class="error">{error}</div>
	{/if}

	<div class="gauges">
		<SensorGauge
			label="RPM" unit="rpm"
			value={$sensorData?.rpm}
			min={0} max={6000}
			warnAt={4500} critAt={5500}
		/>
		<SensorGauge
			label="Speed" unit="mph"
			value={$sensorData?.speed_mph}
			min={0} max={120}
		/>
		<SensorGauge
			label="Coolant" unit="F"
			value={$sensorData?.coolant_temp_f}
			min={100} max={260}
			warnAt={220} critAt={240}
		/>
		<SensorGauge
			label="Throttle" unit="%"
			value={$sensorData?.throttle_pct}
			min={0} max={100}
		/>
		<SensorGauge
			label="Load" unit="%"
			value={$sensorData?.engine_load_pct}
			min={0} max={100}
			warnAt={85} critAt={95}
		/>
		<SensorGauge
			label="Intake" unit="F"
			value={$sensorData?.intake_temp_f}
			min={0} max={200}
			warnAt={150} critAt={180}
		/>
	</div>

	{#if dtcs.length > 0}
		<div class="dtc-panel">
			<h3>Diagnostic Trouble Codes</h3>
			{#each dtcs as dtc}
				<div class="dtc">
					<span class="dtc-code">{dtc.code}</span>
					<span class="dtc-desc">{dtc.description}</span>
					<span class="dtc-status {dtc.status}">{dtc.status}</span>
				</div>
			{/each}
		</div>
	{/if}

	{#if !$sensorData && !error}
		<div class="empty">
			<p>Connect to the OBD-II adapter to see live engine data.</p>
			<p class="hint">Requires an ELM327 adapter connected to the vehicle's OBD-II port.</p>
		</div>
	{/if}
</div>

<style>
	.dashboard {
		padding: 1rem;
	}
	.header {
		display: flex;
		justify-content: space-between;
		align-items: center;
		margin-bottom: 1rem;
	}
	.controls {
		display: flex;
		gap: 0.5rem;
	}
	.gauges {
		display: grid;
		grid-template-columns: repeat(auto-fit, minmax(130px, 1fr));
		gap: 1rem;
		justify-items: center;
		padding: 1rem 0;
	}
	.error {
		padding: 0.5rem 0.75rem;
		background: var(--red-bg);
		color: var(--red);
		border: 1px solid var(--red);
		border-radius: var(--radius);
		margin-bottom: 1rem;
		font-size: 0.85rem;
	}
	.dtc-panel {
		margin-top: 1.5rem;
		padding: 1rem;
		background: var(--bg-surface);
		border: 1px solid var(--border);
		border-radius: var(--radius-lg);
	}
	.dtc-panel h3 {
		color: var(--amber);
		margin-bottom: 0.5rem;
	}
	.dtc {
		display: flex;
		gap: 1rem;
		padding: 0.35rem 0;
		border-bottom: 1px solid var(--border);
		font-size: 0.85rem;
	}
	.dtc-code {
		color: var(--red);
		font-weight: 700;
		min-width: 5ch;
	}
	.dtc-desc { flex: 1; }
	.dtc-status {
		font-size: 0.75rem;
		padding: 0.1rem 0.4rem;
		border-radius: var(--radius);
	}
	.dtc-status.active { background: var(--red-bg); color: var(--red); }
	.dtc-status.pending { background: var(--amber-bg); color: var(--amber); }
	.dtc-status.cleared { background: var(--green-bg); color: var(--green); }
	.empty {
		text-align: center;
		padding: 3rem 1rem;
		color: var(--text-secondary);
	}
	.hint {
		font-size: 0.8rem;
		color: var(--text-muted);
		margin-top: 0.5rem;
	}
</style>
